---
title: "Boston Hot Spots"
author: "Julia Monti & Carrie Fowle"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
---

```{r}

# INSTRUCTIONS

# You are a seasoned data scientist who has just arrived in Boston. You're looking to go see the sights, but you don't know where they are! Instead of buying a tourist guide like a Muggle, you are going to use your skills in exploratory data analysis and visualization to identify some of the cool spots to visit. 

# Working with your partner, conduct analyses to identify at least THREE cool spots that you want to check out. Use the dashboard format to communicate your findings. You can check e.g. on Google to confirm your findings, but you should include clear commentary indicating how your analysis supports your findings. I've included some of the code from the script we worked on together to help you get started. 

```

```{r}
# You may find the following resources useful: 
# - Your team member(s)! 
# - Data wrangling [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf), 
# - `R` graphics [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf), 
# - [`R` Graphics Cookbook](http://www.cookbook-r.com/Graphs/)
# - [RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
```

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(kableExtra)
```

```{r data_prep}
# put your data preparation code here. To get you started, the data preparation we performed in the session previously has already been pasted in. Feel free to add any additional data preparation code needed for your visualizations

listings <- read_csv('../../data/listings.csv')
calendar <- read_csv('../../data/calendar.csv')

source("clean_prices.R")
listings <- clean_prices(listings)
calendar <- clean_prices(calendar)
```


Column {data-width=550}
-----------------------------------------------------------------------

### Heat map of Maximum Prices 

Here we look at the maximum prices during July. We presume that this is the peak of tourist season and that business travel is low. To show finer granularity, listings with a nightly price of more than $1000 USD are excluded.

```{r heatmap}

library(ggmap)

boston_coords <- c(left   = -71.1289, 
				   bottom = 42.3201, 
				   right  = -71.0189, 
				   top    = 42.3701)

basemap <- get_map(location = boston_coords,
				maptype = 'terrain')

deltas = calendar %>%
  filter(month(date) == 7) %>%
  group_by(listing_id) %>%
  summarise(max_p = max(price),
            delta_p = max(price) - min(price)) %>%
  right_join(listings,
             by = c("listing_id" = "id")) %>%
  filter(max_p < 1000)

ggmap(basemap) + 
	geom_point(aes(x = longitude, y = latitude, color = max_p), 
			   data = deltas, 
			   size = .5) +
  labs(color = "Maximum July Price") +
  scale_color_gradient(low = "grey",
                        high = "red")
```



Column {data-width=450}
-----------------------------------------------------------------------

###Average Maximum July Price by Neighborhood

```{r max_by_hood}
deltas %>%
  group_by(neighbourhood) %>%
  summarise(avg_max = mean(max_p, na.rm = TRUE)) %>%
  ggplot() +
  aes(x = reorder(neighbourhood, avg_max),
      y = avg_max) +
  geom_bar(stat = "Identity") +
  theme_minimal() +
  coord_flip() +
  xlab("Neighborhood") +
  ylab("Maximum July Price")
```

### Top Places to Visit

We presume that the most popular places to visit have the highest prices. Based off our analysis of max prices the following neighborhoods seem like hot spots to check out:


```{r top_table}

deltas %>%
  group_by(neighbourhood) %>%
  summarise(avg_max = mean(max_p, na.rm = TRUE)) %>%
  arrange(desc(avg_max)) %>%
  select(neighbourhood) %>%
  head(n = 5) %>%
  rename(Neighborhood = neighbourhood) %>%
  kable()

```

